# Generated by Django 3.2.6 on 2021-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='书名')),
                ('pub', models.CharField(max_length=100, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='零售价')),
            ],
        ),
    ]
